### ISSUE TITLE
rss and other subscription options need improvement

### ISSUE THREAD

**Issue by swiftsam** [CMUBuggy/cmubuggy.org#13]
since the april 2011 site re-launch, many of the rss feeds are broken.  The news feed still works but that's about it.  Gallery and Forum feeds don't work at all.  The Ultimate feed is empty except truncated versions of the news items.

There should be one box on the front page with all subscription options:
- news rss
- news comments rss
- forum rss
- gallery rss
- reference rss
- github rss
- reddit project zone rss
- twitter feed
- facebook page
- linkedin group
- news subscription by e-mail

Ideally all of the rss feeds could be mixed and matched into customized feeds (ie cmubuggy.org/rss/news+forum+github)

**Comment by robsiemb** [comment]
With the demise of feedburner and the reduction of our rss feed support to basically just the one directly provided by wordpress, going to close this as effectively obsolete for now.
