### ISSUE TITLE
newly registered members don't get logged into the forum

### ISSUE THREAD

**Issue by swiftsam** [CMUBuggy/cmubuggy.org#16]
when a user registers a new account at cmubuggy.org, they are added to the cmubuggy/user table.  After that, they need to be added to the user table of each of the site components (forum, gallery, and reference).  This can happen either
- by adding a record to each of those tables when they register
- having those components add a new user automatically when they see a user they don't recognize

I thought the second was happening, but new users seem unable to log in to those parts of the site meaning they are unable to participate.

**Comment by madisonscott** [comment]
We killed site login 😢
