### ISSUE TITLE
non-unique filenames in the gallery get confused in the newsfeed

### ISSUE THREAD

**Issue by swiftsam** [CMUBuggy/cmubuggy.org#18]
Originally noticed by Chris,

"Heya...some of the pictures I uploaded aren't showing up when you view the album...if you type in the url directly, the picture shows up.

I was wondering about it and then I commented on one of the "missing" pictures (http://cmubuggy.org/gallery/2011-2012/2012-04-14/DSCF2090) and then I saw on the front page of cmubuggy.org that it said there were new comments on this picture (http://cmubuggy.org/gallery/Ultimate-Speed/Race-2011/DSCF2090#comments) but there aren't new comments on that picture."

**Comment by robsiemb** [comment]
References obsolete gallery page.  Closing.
