### ISSUE TITLE
inaccuracies in display of results for individual racedays

### ISSUE THREAD

**Issue by swiftsam** [CMUBuggy/cmubuggy.org#2]
Since the new site was debuted in spring '11, some of the race results seem to be screwy.  For example:

Fringe Women's A is not displayed on the Raceday 2010 summary page
http://cmubuggy.org/history/raceday/2010#womens

But their time and place are correct on Fringe's page
http://cmubuggy.org/history/org/fringe

and on the team (entry) page
http://cmubuggy.org/history/team/2010.fringe.WA

**Comment by robsiemb** [comment]
Resolved in new history implementation.
