### ISSUE TITLE
Mobile homepage looks bad with 3 columns

### ISSUE THREAD

**Issue by bebau** [CMUBuggy/cmubuggy.org#231]
It's off-center and the box doesn't contain all the text. Also, the fact that team names are split into 2 lines ("Pika", "A" on a new line) in most cases doesn't look good. Maybe we should just give them each their own section instead of trying for 3 columns on mobile. 

<img src="https://github.com/CMUBuggy/cmubuggy.org/assets/75446868/36d61322-af49-4604-8b83-a2f3dcb4b620" alt="mobile screenshot" width="200"/>

**Comment by robsiemb** [comment]
Nice catch, thank you!
