### ISSUE TITLE
org trophies errors possibly related to DQs

### ISSUE THREAD

**Issue by swiftsam** [CMUBuggy/cmubuggy.org#8]
> galexkeene
> Please see http://cmubuggy.org/history/org/sdc#trophies where SDC is listed as getting 1st and 3rd place, both M and W.
> 
> Obviously your code is not recognizing the blanks from day 2 for SDC (strangely Fringe is also listed as 1st for 2010 on their org page, not sure how we can both be first, weird algorithm).

**Comment by robsiemb** [comment]
Will be resolved in new history implementation.
